### ISSUE TITLE
Persistence settings should be parameterized - causes issues.

### ISSUE THREAD

**Issue by hjorth** [k8s-ruby/k8s-ruby#24]
After this PR has been merged to Kubernetes https://github.com/kubernetes/kubernetes/pull/103958

There is issues with long-time running connections (with no activity).

example:

```
require 'k8s-ruby'

K8s::Logging.debug!
K8s::Transport.verbose!

client = K8s::Client.config(
  K8s::Config.load_file(
    File.expand_path '~/.kube/config'
  )
)

sleep_seconds = 120

client.api('v1').resource('pods', namespace: 'default').list().each do |pod|
    puts "namespace=#{pod.metadata.namespace} pod: #{pod.metadata.name} node=#{pod.spec.nodeName}"
end

puts "Now sleeping #{sleep_seconds}"

while sleep_seconds > 0
    puts "Countdown - #{sleep_seconds} SECONDS(S) LEFT!"
    sleep_seconds -= 1
    sleep 1
end 
client.api('v1').resource('pods', namespace: 'default').list().each do |pod|
    puts "namespace=#{pod.metadata.namespace} pod: #{pod.metadata.name} node=#{pod.spec.nodeName}"
end

```

This fails with:
```
Traceback (most recent call last):
	11: from k8s.rb:27:in `<main>'
	10: from /var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource_client.rb:201:in `list'
	 9: from /var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource_client.rb:210:in `meta_list'
	 8: from /var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/transport.rb:284:in `request'
	 7: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/connection.rb:282:in `request'
	 6: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/connection.rb:451:in `response'
	 5: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/middlewares/redirect_follower.rb:82:in `response_call'
	 4: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
	 3: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/response.rb:63:in `parse'
	 2: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/response.rb:63:in `loop'
	 1: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/response.rb:64:in `block in parse'
/var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/socket.rb:65:in `readline': EOFError (EOFError)
	11: from k8s.rb:27:in `<main>'
	10: from /var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource_client.rb:201:in `list'
	 9: from /var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource_client.rb:210:in `meta_list'
	 8: from /var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/transport.rb:284:in `request'
	 7: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/connection.rb:282:in `request'
	 6: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/connection.rb:451:in `response'
	 5: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/middlewares/redirect_follower.rb:82:in `response_call'
	 4: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
	 3: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/response.rb:63:in `parse'
	 2: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/response.rb:63:in `loop'
	 1: from /var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/response.rb:64:in `block in parse'
/var/lib/gems/2.7.0/gems/excon-0.89.0/lib/excon/socket.rb:65:in `readline': EOFError (EOFError) (Excon::Error::Socket)
```
in lib/k8s/transport.rb - changing line 173 - from persistent: true to persistent: false - seems to solve the issue.

So I suggest that the persistence can be overridden when initiating the client.

**Comment by hjorth** [comment]
I found the answer..
```
client = K8s::Client.config(
  K8s::Config.load_file(
    File.expand_path '~/.kube/config'
  ),
  persistent: false
)
```
