### ISSUE TITLE
Error: undefined method `build' for Dry::Logic::Rule::Predicate:Class

### ISSUE THREAD

**Issue by Vasu1105** [k8s-ruby/k8s-ruby#33]
Getting below error with the latest k8s-ruby. I have also raised this issue in Dry logic but according to them the versions of dry-types and dry-logic  needs to be updated. Ref: https://github.com/dry-rb/dry-logic/issues/103

```
[2022-11-14T13:13:23+05:30] ERROR: Error: undefined method `build' for Dry::Logic::Rule::Predicate:Class
[2022-11-14T13:13:23+05:30] ERROR: Exception: NoMethodError
[2022-11-14T13:13:23+05:30] ERROR: Trace: /Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types/constraints.rb:20:in `block in Rule'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types/constraints.rb:19:in `each'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types/constraints.rb:19:in `map'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types/constraints.rb:19:in `Rule'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types/builder.rb:56:in `constrained'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types/core.rb:56:in `block in <module:Types>'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types/core.rb:55:in `each'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types/core.rb:55:in `<module:Types>'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types/core.rb:6:in `<module:Dry>'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types/core.rb:5:in `<top (required)>'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types.rb:207:in `require'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry/types.rb:207:in `<top (required)>'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry-types.rb:3:in `require'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/dry-types-1.4.0/lib/dry-types.rb:3:in `<top (required)>'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/k8s-ruby-0.12.0/lib/k8s/api.rb:3:in `require'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/k8s-ruby-0.12.0/lib/k8s/api.rb:3:in `<top (required)>'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/k8s-ruby-0.12.0/lib/k8s/api/metav1.rb:3:in `require'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/k8s-ruby-0.12.0/lib/k8s/api/metav1.rb:3:in `<top (required)>'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/k8s-ruby-0.12.0/lib/k8s/client.rb:11:in `require'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/k8s-ruby-0.12.0/lib/k8s/client.rb:11:in `<top (required)>'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/k8s-ruby-0.12.0/lib/k8s-ruby.rb:4:in `require_relative'
/Users/vjagdale/.rvm/gems/ruby-2.7.0/gems/k8s-ruby-0.12.0/lib/k8s-ruby.rb:4:in `<top (required)>'
/Users/vjagdale/workspace/train-kubernetes/lib/train-kubernetes/connection.rb:2:in `require'
/Users/vjagdale/workspace/train-kubernetes/lib/train-kubernetes/connection.rb:2:in `<top (required)>'
/Users/vjagdale/workspace/train-kubernetes/lib/train-kubernetes/transport.rb:1:in `require'
/Users/vjagdale/workspace/train-kubernetes/lib/train-kubernetes/transport.rb:1:in `<top (required)>'
/Users/vjagdale/workspace/train-kubernetes/lib/train-kubernetes.rb:19:in `require'
/Users/vjagdale/workspace/train-kubernetes/lib/train-kubernetes.rb:19:in `<top (required)>'
```

**Comment by matti** [comment]
@Vasu1105 please open the PR again

**Comment by Vasu1105** [comment]
@matt could you please let me know if should we have `Gemfile. lock` committed?  I am not sure because on each different ruby version the Gemfile.lock is different

**Comment by matti** [comment]
fixed now I guess
